# Generated by Django 4.2.5 on 2023-09-20 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warcarftApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('musics', models.FileField(upload_to='audio/')),
            ],
        ),
        migrations.CreateModel(
            name='Replicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('replicas', models.FileField(upload_to='audio/')),
            ],
        ),
        migrations.DeleteModel(
            name='Audio',
        ),
    ]
