# Generated by Django 4.2.5 on 2023-09-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warcarftApp', '0002_musics_replicas_delete_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinematic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('cinematic_video', models.FileField(upload_to='video/')),
            ],
        ),
        migrations.CreateModel(
            name='GameProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('game_process_video', models.FileField(upload_to='video/')),
            ],
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
